# Generated by Django 3.2.8 on 2021-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211101_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_futured',
            field=models.BooleanField(default=False),
        ),
    ]
