# Generated by Django 3.2.8 on 2021-12-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_futured',
            field=models.BooleanField(default=False),
        ),
    ]
