# Generated by Django 3.2.8 on 2021-12-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_category_is_futured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_futured',
            field=models.BooleanField(default=True),
        ),
    ]
